services:
  app:
    build:
      context: .
      target: development
    container_name: swiftapp-dev
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swift-dev-nginx-http.rule=Host(`swiftapp.localhost`)"
      - "traefik.http.routers.swift-dev-nginx-http.entrypoints=web"
      # - "traefik.http.services.swift-dev-nginx-http.loadbalancer.server.port=80"
      - "traefik.http.services.swift-dev-nginx-http.loadbalancer.server.port=5173"
    ports:
      - "5173:5173"
    env_file:
      - .env.dev
    command: ["npm", "run", "dev"]
    stdin_open: true
    tty: true
    networks:
      - traefik

networks:
  traefik:
    external: true
