services:
  app-prod:
    build:
      context: .
      target: production
    container_name: app-prod
    # ports:
    #   - "80:80"
    # env_file:
    #   - .env

    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main_app.entrypoints=https"
      - "traefik.http.routers.main_app.rule=Host(`swiftapp.ch`)"
      - "traefik.http.routers.main_app.tls=true"
      - "traefik.http.routers.main_app.tls.certresolver=cloudflare"
      - "traefik.http.routers.main_app.tls.domains[0].main=swiftapp.ch"
      - "traefik.http.routers.main_app.tls.domains[0].sans=*.swiftapp.ch"
      - "traefik.http.services.main_app.loadbalancer.server.port=80"

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
networks:
  traefik_proxy:
    external: true
